### ISSUE TITLE
AllJoyn MVVM Storage Prototyp 

### ISSUE THREAD

**Issue by niko-achilles** [intui/myenvironment#3]
Abstract Communication between Sensor Data and fake Data. 
MVVM Prototyp for Separation  of Concerns
learn File Storage UWP and integrate the in this Prototyp

**Comment by niko-kokkinos** [comment]
pushed the project here. https://github.com/niko-kokkinos/AllJoynTemperatureHumidity

**Comment by niko-kokkinos** [comment]
updated the app. humidity parts added. Now App supports Temperature and Humidity via AllJoyn
